### PR TITLE
Bump version to 0.4.0

### PR DESCRIPTION
**Pull request by literalpie**
This release will include support for parameters and allow the addon to be included in the storybook addon catalog.

### CODE REVIEW

**Comment by literalpie** [comment]
@unindented I think you need to publish the release to npm (or if it's possible for me to do it, I don't know how)

**Comment by unindented** [comment]
@literalpie I think I configured things so that tagging a commit and pushing it would cause Travis to automatically publish to npm (the encrypted npm token seems to be [here](https://github.com/unindented/storybook-addon-rtl/blob/cbef24878e3b946d4d435b94885d6a0df13a834f/.travis.yml#L8-L9)).

I'd be surprised if it still worked though. Either the token has expired, or Travis has changed something on their side.

Do you have a username on npm, so that I can add you as maintainer of the package?

**Comment by literalpie** [comment]
@unindented I am "bkindle" on npm

**Comment by literalpie** [comment]
I think [this](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) might be why it doesn't work any more. travis-ci.org projects need to be migrated to travis-ci.com.

**Comment by unindented** [comment]
@literalpie I've added you as maintainer on npm, so now you can do all the things. Thank you for your help!

**Pull request merged**
