### PR TITLE
build: update dependencies

### LINKED ISSUE #8: Storybook v5
I'm using your addon with satisfaction, thank you, but I would like to notify something.
I installed the latest version of storybook (5.2.6) and your addon works with this version as well, although your `package.json` requires `<=4` as a peer dependency, so I have the following warning:
```
npm WARN storybook-addon-rtl@0.2.2 requires a peer of @storybook/addons@^3.1.6 || 4.x but none is installed. You must install peer dependencies yourself.
```
Based on my experiences, you can update your restrictions to the new version as well.

### PR DESCRIPTION
**Pull request by literalpie**
This hasn't been updated in a while, but I hope you'll accept this. There are two main reasons I think this is worth updating:
* With the release of NPM v7, peerDependencies become more strict. The update to `@storybook/addons` is important to avoid these errors for anyone who is using this package in their project.
* Security updates are always good. There were multiple vulnerabilities reported by `npm audit`. This probably isn't a big deal because I don't think they affected any code shipped to consumers of the add-on, but I think it's still worth fixing.

I went ahead and updated all dependencies, but let me know if you want me to strip it down to only update the important things mentioned above.
Also, let me know if you would like me to change the `@storybook/addons` version to `*` to avoid needing to do this again.

Closes #8

### CODE REVIEW

**Comment by literalpie** [comment]
@unindented could you please take a look at this? I'd really love to see it get merged

**Comment by unindented** [comment]
Thank you so much!

@literalpie would you be interested in maintaining this project? I don't have the time these days...

**Comment by unindented** [comment]
I've now published `v0.3.0` with your changes.

**Comment by literalpie** [comment]
@unindented sure, I think I can maintain this

**Comment by unindented** [comment]
@literalpie ok, sent you an invite.

**Pull request merged**
